# Generated by Django 4.1 on 2023-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=2200, null=True)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('dateCreate', models.DateField(blank=True, max_length=350, null=True)),
                ('img', models.CharField(blank=True, max_length=900, null=True)),
            ],
        ),
    ]
